spring:
  profiles:
    active: local

---
server:
  port: 8080
  servlet:
    session:
      timeout: 1800

spring:
  config:
    activate:
      on-profile: local

  h2:
    console:
      enabled: true

#  datasource:
#    driver-class-name: org.h2.Driver
#    url: jdbc:h2:~/want
#    username: sa
#    password: 1234

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/want
    username: root
    password: 1234

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        show_sql: true
        default_batch_fetch_size: 100
    defer-datasource-initialization: true
    #database-platform: org.hibernate.dialect.H2Dialect
    database-platform: org.hibernate.dialect.MySQL8Dialect
  sql:
    init:
      mode: always

logging:
  level:
    com.trip.want: debug
    org.hibernate.sql: debug
